# Generated by Django 5.2.7 on 2025-10-08 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetballers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voetballers',
            new_name='Voetballer',
        ),
    ]
